let all = document.getElementById("all");
let youtube = document.getElementById("youtube");
let vimeo = document.getElementById("vimeo");
let soundcloud = document.getElementById("soundcloud");
let popup = document.getElementById("popup");
let content = document.getElementById("content");
let divOne = document.getElementById("des-1");
let divtwo = document.getElementById("des-2");
let divThree = document.getElementById("des-3");
let divFour = document.getElementById("des-4");
let divFive = document.getElementById("des-5");
let divSix = document.getElementById("des-6");
all.addEventListener("click", function () {
  divOne.style.display = "block";
  divtwo.style.display = "block";
  divThree.style.display = "block";
  divFour.style.display = "block";
  divFive.style.display = "block";
  divSix.style.display = "block";
  all.style.color = "#00C0FF";
  youtube.style.color = "white";
  vimeo.style.color = "white";
  soundcloud.style.color = "white";
  popup.style.color = "white";
  content.style.color = "white";
});
youtube.addEventListener("click", function () {
  divOne.style.display = "block";
  divtwo.style.display = "none";
  divThree.style.display = "none";
  divFour.style.display = "none";
  divFive.style.display = "none";
  divSix.style.display = "none";
  all.style.color = "white";
  youtube.style.color = "#00C0FF";
  vimeo.style.color = "white";
  soundcloud.style.color = "white";
  popup.style.color = "white";
  content.style.color = "white";
});
vimeo.addEventListener("click", function () {
  divOne.style.display = "none";
  divtwo.style.display = "block";
  divThree.style.display = "none";
  divFour.style.display = "none";
  divFive.style.display = "none";
  divSix.style.display = "none";
  all.style.color = "white";
  youtube.style.color = "white";
  vimeo.style.color = "#00C0FF";
  soundcloud.style.color = "white";
  popup.style.color = "white";
  content.style.color = "white";
});
soundcloud.addEventListener("click", function () {
  divOne.style.display = "none";
  divtwo.style.display = "none";
  divThree.style.display = "block";
  divFour.style.display = "none";
  divFive.style.display = "none";
  divSix.style.display = "none";
  all.style.color = "white";
  youtube.style.color = "white";
  vimeo.style.color = "white";
  soundcloud.style.color = "#00C0FF";
  popup.style.color = "white";
  content.style.color = "white";
});
popup.addEventListener("click", function () {
  divOne.style.display = "none";
  divtwo.style.display = "none";
  divThree.style.display = "none";
  divFour.style.display = "block";
  divFive.style.display = "block";
  divSix.style.display = "none";
  all.style.color = "white";
  youtube.style.color = "white";
  vimeo.style.color = "white";
  soundcloud.style.color = "white";
  popup.style.color = "#00C0FF";
  content.style.color = "white";
});
content.addEventListener("click", function () {
  divOne.style.display = "none";
  divtwo.style.display = "none";
  divThree.style.display = "none";
  divFour.style.display = "none";
  divFive.style.display = "none";
  divSix.style.display = "block";
  all.style.color = "white";
  youtube.style.color = "white";
  vimeo.style.color = "white";
  soundcloud.style.color = "white";
  popup.style.color = "white";
  content.style.color = "#00C0FF";
});
